logging:
    file:
        name: /tmp/client.log
spring:
    ai:
        ollama:
            chat:
                model: qwen2.5
                options:
                    seed: 123456789
                    temperature: 0.9
            base-url: http://localhost:11434

        mcp:
            client:
                stdio:
                    servers-configuration: "classpath:/mcp-servers-config.json"
                type: sync
    application:
        name: AssistantClient
    main:
        web-application-type: none

