logging:
    level:
        io:
            modelcontextprotocol:
                client: DEBUG
                spec: DEBUG
    file:
        name: /tmp/client.log
    pattern:
        console:
spring:
    ai:
        mcp:
            client:
                sse:
                    connections:
                        weather:
                            url: http://localhost:8080
                stdio:
                    servers-configuration: "classpath:/mcp-servers-config.json"
        anthropic:
            api-key: ${ANTHROPIC_API_KEY}
    application:
        name: AssistantClient
    main:
        web-application-type: none
        banner-mode: log

